export type QueryErrorCode = 'xxx'
    | 'field:invalid' | 'field:empty'
    | 'field:raw-both' | 'field:raw-none'
    | 'as:invalid'
    | 'raw:invalid' | 'raw:empty'
    | 'op:invalid-key' | 'op:invalid-type'
    | 'asc:invalid-key' | 'asc:invalid-type'
    | 'value:invalid-type' | 'value:invalid-item'
    | 'integer:invalid' | 'integer:min'
    | 'select:item' | 'select:body'
    | 'where:item' | 'where:body'
    | 'having:item' | 'having:body'
    | 'groupBy:item' | 'groupBy:body'
    | 'orderBy:item' | 'orderBy:body'
    | 'page:conflict'
    | 'limit:conflict'
    | 'pagination:invalid-key'
    | 'pagination:invalid-type';
